using System;
using System.Collections.Generic;

namespace MailRoom.Model
{
    public partial class Cms15001Conf
    {
        public string ClaimId { get; set; }
        public float? IaPayerName { get; set; }
        public float? IbPayerAddress1 { get; set; }
        public float? IcPayerAddress2 { get; set; }
        public float? IdPayerCityStateZipcode { get; set; }
        public float? _1PayerType { get; set; }
        public float? _1aInsuredIdNumber { get; set; }
        public float? _2aLastName { get; set; }
        public float? _2bSuffix { get; set; }
        public float? _2cFirstName { get; set; }
        public float? _2dMiddleName { get; set; }
        public float? _3aMm { get; set; }
        public float? _3bDd { get; set; }
        public float? _3cYyyy { get; set; }
        public float? _3dGender { get; set; }
        public float? _4aLastName { get; set; }
        public float? _4bSuffix { get; set; }
        public float? _4cFirstName { get; set; }
        public float? _4dMiddleName { get; set; }
        public float? _5aStreetAddress { get; set; }
        public float? _5bCity { get; set; }
        public float? _5cState { get; set; }
        public float? _5dZipcode { get; set; }
        public float? _5eTelephoneAreacode { get; set; }
        public float? _5fTelephonePhoneNumber { get; set; }
        public float? _6PatientRelationshipToInsured { get; set; }
        public float? _7aStreetAddress { get; set; }
        public float? _7bCity { get; set; }
        public float? _7cState { get; set; }
        public float? _7dZipCode { get; set; }
        public float? _7eTelephoneAreacode { get; set; }
        public float? _7fTelephonePhonenumber { get; set; }
        public float? _8ReservedForNuccUse { get; set; }
        public float? _9ALastName { get; set; }
        public float? _9BSuffix { get; set; }
        public float? _9CFirstName { get; set; }
        public float? _9DMiddleName { get; set; }
        public float? _9aOtherPoliciesNumber { get; set; }
        public float? _9bReservedForNuccUse { get; set; }
        public float? _9cReservedForNuccUse { get; set; }
        public float? _9dInsuranceplanName { get; set; }
        public float? _10aEmployment { get; set; }
        public float? _10bAutoAccident { get; set; }
        public float? _10bAAutoAccidentPlace { get; set; }
        public float? _10cOtherAccident { get; set; }
        public float? _10dClaimCodes { get; set; }
        public float? _11InsuredsPolicyNumber { get; set; }
        public float? _11aAMm { get; set; }
        public float? _11aBDd { get; set; }
        public float? _11aCYyyy { get; set; }
        public float? _11aDGender { get; set; }
        public float? _11bAQualifier { get; set; }
        public float? _11bBClaimId { get; set; }
        public float? _11cInsurancePlanName { get; set; }
        public float? _11dAnotherHealthBenefitPlan { get; set; }
        public float? _12ASignatureUrl { get; set; }
        public float? _12BAMm { get; set; }
        public float? _12BBDd { get; set; }
        public float? _12BCYyyy { get; set; }
        public float? _13InsuredsAuthorizedSignatureUrl { get; set; }
        public float? _14AMm { get; set; }
        public float? _14BDd { get; set; }
        public float? _14CYyyy { get; set; }
        public float? _14DQualifier { get; set; }
        public float? _15AMm { get; set; }
        public float? _15BDd { get; set; }
        public float? _15CYyyy { get; set; }
        public float? _15DQualifier { get; set; }
        public float? _16AMm { get; set; }
        public float? _16BDd { get; set; }
        public float? _16CYyyy { get; set; }
        public float? _16AAMm { get; set; }
        public float? _16ABDd { get; set; }
        public float? _16ACYyyy { get; set; }
        public float? _17Qualifier { get; set; }
        public float? _17AName { get; set; }
        public float? _17aAQualifier { get; set; }
        public float? _17aBIdNumber { get; set; }
        public float? _17bIdNumber { get; set; }
        public float? _18AMm { get; set; }
        public float? _18BDd { get; set; }
        public float? _18CYyyy { get; set; }
        public float? _18AAMm { get; set; }
        public float? _18ABDd { get; set; }
        public float? _18ACYyyy { get; set; }
        public float? _19AdditionalClaimInformation { get; set; }
        public float? _20YesOrNo { get; set; }
        public float? _20AChargesDollars { get; set; }
        public float? _20BChargesCents { get; set; }
        public float? _21IcdIndicator { get; set; }
        public float? _21aNatureOfIllnes { get; set; }
        public float? _21bNatureOfIllnes { get; set; }
        public float? _21cNatureOfIllnes { get; set; }
        public float? _21dNatureOfIllnes { get; set; }
        public float? _21eNatureOfIllnes { get; set; }
        public float? _21fNatureOfIllnes { get; set; }
        public float? _21gNatureOfIllnes { get; set; }
        public float? _21hNatureOfIllnes { get; set; }
        public float? _21iNatureOfIllnes { get; set; }
        public float? _21jNatureOfIllnes { get; set; }
        public float? _21kNatureOfIllnes { get; set; }
        public float? _21lNatureOfIllnes { get; set; }
        public float? _22AReSubmissionCodeQualifier { get; set; }
        public float? _22BOriginalRefNo { get; set; }
        public float? _23PriorAuthorizationNumber { get; set; }
        public float? _24TableConfidence { get; set; }
        public float? _25AType { get; set; }
        public float? _25BIdNumber { get; set; }
        public float? _26PatientAccNumber { get; set; }
        public float? _27AcceptAssignment { get; set; }
        public float? _28ADollars { get; set; }
        public float? _28BCents { get; set; }
        public float? _29ADollars { get; set; }
        public float? _29BCents { get; set; }
        public float? _30ACode { get; set; }
        public float? _30BQualifier { get; set; }
        public float? _31ASignature { get; set; }
        public float? _31BAMm { get; set; }
        public float? _31BBDd { get; set; }
        public float? _31BCYyyy { get; set; }
        public float? _32AProviderName { get; set; }
        public float? _32BProviderAddress { get; set; }
        public float? _32CCityStateZipcode { get; set; }
        public float? _32aNationalProviderIdentifierNumber { get; set; }
        public float? _32bPayerAssignedIdentifierOfBillingProvider { get; set; }
        public float? _33AAreaCode { get; set; }
        public float? _33BPhoneNumber { get; set; }
        public float? _33CBillingProviderName { get; set; }
        public float? _33DBillingProviderAddress { get; set; }
        public float? _33EBillingproviderCityStateZipcode { get; set; }
        public float? _33aNationalProviderIdentifierNumber { get; set; }
        public float? _33bPayerAssignedIdentifierOfBillingProvider { get; set; }
        public float? OverallTableConfidence { get; set; }

        public Cms15001 Claim { get; set; }
    }
}
